### ISSUE TITLE
`orders[][items][][isCanceled]` is not available in Python API

### ISSUE THREAD

**Issue by Inilien** [retailcrm/api-client-python#20]
for the [order GET method](https://help.retailcrm.ru/Developers/ApiVersion5#get--api-v5-orders) there is a field `orders[][items][][isCanceled]` in the documentation.  
But I do not see in in the Python results of the method.

**Comment by Neur0toxine** [comment]
Hello!

This library doesn't modify response data. It uses `requests` library as an API client, which does deserialization of request data under the hood. Target data type is chosen automatically (it depends on received JSON structure).

Therefore, we can't help you with your request by modifying this library.

I'd recommend you to contact technical support.
