### ISSUE TITLE
Неочевидное self.parameters

### ISSUE THREAD

**Issue by customr** [retailcrm/api-client-python#24]
Доброго времени суток!
Долго не мог понять, из-за чего некоторые запросы вызывали ошибку
При одном и том же наборе данных ошибка то вызывалась, то нет
И как оказалось, некоторые параметры с прошлых запросов по API-клиенту **могут попасть** в параметры других запросов, где они **не нужны** и соответственно могут вызвать ошибки
Обратите внимание на self.parameters, он никогда не опустошается, а лишь дополняются новыми данными
Сам метод запроса API:
```python
def post(self, url, version=True):
    """
    Post request
    :return: Response
    """
    base_url = self.api_url + '/' + self.api_version if version else self.api_url
    requests_url = base_url + url
    response = requests.post(requests_url, data=self.parameters, headers={
        'X-API-KEY': self.api_key})
    
    return Response(response.status_code, response.json())
```
Пример метода API-клиента, где нет параметра "filter":
```python
def order_create(self, order, site=None):
    """
    :param order: object
    :param site: string
    :return: Response
    """
    self.parameters['order'] = json.dumps(order)

    if site is not None:
        self.parameters['site'] = site

    return self.post('/orders/create')
```

Пример метода API-клиента, где есть параметр "filter":
```python
def orders(self, filters=None, limit=20, page=1):
    """
    :param filters: object
    :param limit: integer
    :param page: integer
    :return: Response
    """
    self.parameters['filter'] = filters
    self.parameters['limit'] = limit
    self.parameters['page'] = page

    return self.get('/orders')
```

Соответственно если изначально вызвать метод orders, self.parameters будет содержать в себе поля filter, limit, page
Затем если вызвать order_create, помимо полей order и site, которые там необходимы, там будут еще и содержаться поля filter, limit, page.
Из-за чего и вызывается ошибка, как правило "Not found", которая не очень информативна для дебага :)

**Comment by gwinn** [comment]
Спасибо за замечание и вклад в проект :slightly_smiling_face:
