### ISSUE TITLE
API v4

### ISSUE THREAD

**Issue by dimanjy** [retailcrm/api-client-python#3]
В документации API v3 значится устаревшим. До v4 планируется обновление?

**Comment by gwinn** [comment]
Планируется мультиверсионный клиент, аналогичный [api-client-php](https://github.com/retailcrm/api-client-php)

Вы можете подписаться на уведомления для этого репозитория, что бы сразу узнать о релизе.

**Comment by gwinn** [comment]
Выкатили предварительную версию нового api клиента
